# Jekyll configuration file
# Exclude directories and files that shouldn't be processed

# Site settings
title: Maps Project
description: A comprehensive mapping application with web, mobile, and server components
name: Maps Project
url: "https://syntaxsociety6.github.io"
baseurl: "/Maps"

# Exclude node_modules and other build artifacts
exclude:
  - node_modules/
  - server/node_modules/
  - web/node_modules/
  - mobile/node_modules/
  - SunHack/node_modules/
  - SunHack/packages/*/node_modules/
  - .git/
  - package.json
  - package-lock.json
  - requirements.txt
  - *.pyc
  - __pycache__/
  - .env
  - .env.local
  - .env.production

# Include only markdown and asset files
include:
  - README.md
  - "*.md"
  - "*.html"
  - "*.css"
  - "*.js"
  - "*.json"
  - "*.yml"
  - "*.yaml"

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: pretty
encoding: utf-8

# Theme settings
theme: jekyll-theme-minimal

# Plugins
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
